// <auto-generated />
namespace _2011063410_ChuMinhKhai.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InitiaModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitiaModels));
        
        string IMigrationMetadata.Id
        {
            get { return "202303071353573_InitiaModels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
